"""Project-wide configuration defaults."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATASET_PATH = PROJECT_ROOT / "Train Set (Labeled)-20260405T164823Z-3-001.zip"
CACHE_DIR = PROJECT_ROOT / ".cache"

RANDOM_SEED = 42
DEFAULT_IMAGE_SIZE = None
DEFAULT_MAX_IMAGES = None
DEFAULT_MAX_IMAGES_PER_PERSON = 0

DEFAULT_VALIDATION_RATIO = 0.2
DEFAULT_OUTER_FOLDS = 5
DEFAULT_INNER_FOLDS = 3

DEFAULT_COMPONENT_GRID = (50, 100, 200, 363)
DEFAULT_SVM_REG_GRID = (1e-4, 1e-3, 1e-2)
DEFAULT_SVM_EPOCHS_GRID = (20, 50)
DEFAULT_SVM_LEARNING_RATE_GRID = (0.1, 0.2)
DEFAULT_KNN_NEIGHBORS = (1, 3, 5,)
DEFAULT_KNN_BATCH_SIZE = 128
